import { GAME_HEIGHT, GAME_WIDTH } from '../../core/gameConstants';

export const UI_METRICS = Object.freeze({
  canvas: { width: GAME_WIDTH, height: GAME_HEIGHT },
  spacing: {
    micro: 4,
    internal: 8,
    compact: 12,
    module: 16,
    section: 24,
  },
  panel: {
    margin: 16,
    gap: 10,
    padding: 14,
    cornerRadius: 14,
    borderWidth: 2,
    shadowOffset: 5,
  },
  button: {
    compactHeight: 32,
    height: 40,
    primaryHeight: 52,
    cornerRadius: 10,
    borderWidth: 2,
    repeatGuardMs: 180,
  },
  statCard: {
    height: 44,
    cornerRadius: 9,
  },
  slot: {
    width: 80,
    height: 76,
    cornerRadius: 12,
    borderWidth: 2,
    heroRadius: 14,
    heroMainDisplaySize: 78,
    heroEchoDisplaySize: 40,
    heroMaximumDisplaySize: 84,
    backgroundTop: -24,
    runeY: -7,
    nameY: 24,
    detailY: 43,
    heroTextSafeTop: 17,
    foregroundLipHeight: 2,
    foregroundLipWidth: 58,
    foregroundLipBottomInset: 8,
    foregroundLipAlpha: 0.55,
    selectedOutlineGap: 2,
    selectedOutlineWidth: 2,
    hoverFrameInset: 3,
    selectedMarkerSize: 6,
    selectedMarkerInsetX: 5,
    selectedMarkerInsetY: 5,
    baseAuraOffsetY: -4,
    maximumStarAuraOffsetY: -9,
  },
  layout: {
    topBar: { x: 16, y: 6, width: 1248, height: 58 },
    battlefield: { x: 16, y: 66, width: 1248, height: 434 },
    commandDeck: { x: 16, y: 508, width: 1248, height: 212 },
    rightDrawer: {
      x: 1_020,
      y: 76,
      width: 236,
      height: 384,
      collapsedX: 1_210,
      collapsedY: 82,
      collapsedWidth: 46,
      collapsedHeight: 32,
      tabTop: 14,
      tabHeight: 32,
      bodyTop: 56,
      bodyPadding: 12,
    },
    bottomCommand: {
      paddingX: 16,
      paddingY: 8,
      columnGap: 16,
      leftColumnWidth: 296,
      rightColumnWidth: 296,
      sectionLabelHeight: 12,
      statRowTop: 20,
      secondaryRowTop: 72,
      secondaryButtonTop: 128,
      helperTextTop: 176,
      primaryButtonTop: 72,
      actionRowTop: 148,
      selectedInfoTop: 0,
      selectedInfoHeight: 28,
      heroBoardTopRowBaseCenterY: 76,
      firstRowVerticalAdjustment: -5,
      heroBoardBottomRowBaseCenterY: 158,
      secondRowVerticalAdjustment: -5,
      heroBoardBottomSafePadding: 4,
    },
    battleCenterX: GAME_WIDTH / 2,
    battleCenterY: 285,
  },
  animation: {
    fast: 120,
    normal: 220,
    slow: 420,
    noticeHold: 1050,
    coreDamage: 180,
    waveNotice: 1450,
  },
  depth: {
    backdrop: 0,
    battlefield: 4,
    units: 12,
    commandDeck: 30,
    hud: 40,
    notice: 70,
    overlay: 90,
    debug: 110,
  },
});
